# Generated by Django 5.2.17 on 2026-09-24 16:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('registration_open', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tish boshlanishi")),
                ('registration_close', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tish tugashi")),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Olimpiada sanasi')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Olimpiada',
                'verbose_name_plural': 'Olimpiadalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda bo'lishi kerak: +998XXXXXXXXX", regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqami')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('school', models.CharField(max_length=255, verbose_name='Maktab nomi')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman/shahar')),
                ('class_number', models.PositiveSmallIntegerField(choices=[(5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf'), (9, '9-sinf'), (10, '10-sinf'), (11, '11-sinf')], verbose_name='Sinf')),
                ('teacher_name', models.CharField(blank=True, max_length=255, verbose_name="O'qituvchi F.I.Sh.")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='participants.olympiadevent', verbose_name='Olimpiada')),
            ],
            options={
                'verbose_name': 'Qatnashchi',
                'verbose_name_plural': 'Qatnashchilar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='participant_phone_59df7f_idx'), models.Index(fields=['full_name'], name='participant_full_na_8e42a4_idx'), models.Index(fields=['school'], name='participant_school_a0912e_idx'), models.Index(fields=['district'], name='participant_distric_e6c0c5_idx'), models.Index(fields=['class_number'], name='participant_class_n_1b7829_idx'), models.Index(fields=['created_at'], name='participant_created_f2bfe0_idx')],
                'unique_together': {('event', 'phone')},
            },
        ),
    ]
