# Generated by Django 5.2.17 on 2026-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha/Izoh (ixtiyoriy)')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Sertifikat / Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rsatilsin")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
            ],
            options={
                'verbose_name': 'Sertifikat / Galereya rasmi',
                'verbose_name_plural': 'Sertifikatlar va Galereya',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
