# Generated by Django 5.2.17 on 2026-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='class_number',
            field=models.PositiveSmallIntegerField(choices=[(5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf')], verbose_name='Sinf'),
        ),
    ]
