# Generated by Django 5.2.17 on 2026-09-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_class_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Hackathon IT School', max_length=255, verbose_name='Sayt/Maktab nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Sayt Logotipi (PNG/SVG/JPG)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Hero (Bosh sahifa) asosiy rasmi')),
                ('school_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Maktab haqida bo'limi rasmi")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi tahrirlangan')),
            ],
            options={
                'verbose_name': 'Sayt Rasmlari va Logotip',
                'verbose_name_plural': 'Sayt Rasmlari va Logotip sozlamalari',
            },
        ),
    ]
