# Generated by Django 5.2.17 on 2026-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_sitemediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tuman/shahar'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Maktab nomi'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='teacher_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="O'qituvchi F.I.Sh."),
        ),
    ]
