# Generated by Django 5.2.17 on 2026-10-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participant_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='class_number',
            field=models.PositiveSmallIntegerField(choices=[(5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf')], verbose_name='Sinf'),
        ),
    ]
