# Generated by Django 5.2.17 on 2026-10-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_alter_participant_class_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
    ]
